# Generated by Django 4.1.5 on 2023-03-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
