# Generated by Django 4.1.5 on 2023-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
